# Generated by Django 2.1.1 on 2018-09-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('menasgem', models.TextField()),
                ('receber_noticia', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
